name: called workflow

on:
  workflow_call:
    inputs:
      test:
        required: true
        type: string

jobs:
  first_step:
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ inputs.test }}
      name: just say something