name: caller workflow

on: 
  push

env: 
  DAY_OF_WEEK: Monday



jobs:
  called_workflow:
    # uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    uses: ./.github/workflows/called.yaml
    with:
      test: "hello patrick"


  called_workflow_2:
    uses: munnep-practice/workflows/.github/workflows/called.yaml@main
    # uses: ./.github/workflows/called.yaml
    with:
      test: "hello patrick"      

   
  second_step:
    runs-on: ubuntu-latest
    steps:
    - run: echo Today is ${{ env.DAY_OF_WEEK }} or $DAY_OF_WEEK
      name: just say something

