name: caller workflow

on: 
  push

jobs:
  called workflow:
    # uses: octo-org/example-repo/.github/workflows/reusable-workflow.yml@main
    uses: ./.github/workflows/called.yaml
    with:
      test: "hello patrick"

   
  second step:
    runs-on: ubuntu-latest
    steps:
    - run: echo second step
      name: just say something